// Test data seeding script for development
export const testCities = [
  {
    id: "malta",
    cityName: "Malta",
    country: "Malta",
    region: "Malta",
    averagePrice: 45.5,
    currency: "USD",
    totalListings: 1250,
    lastUpdated: new Date(),
    dataSource: {
      url: "https://data.insideairbnb.com/malta/2025-03-18/data/listings.csv.gz",
      scrapedDate: "2025-03-18",
    },
    priceBreakdown: {
      entirePlace: 55.2,
      privateRoom: 35.8,
      sharedRoom: 25.0,
    },
  },
  {
    id: "porto",
    cityName: "Porto",
    country: "Portugal",
    region: "Norte",
    averagePrice: 52.3,
    currency: "USD",
    totalListings: 2100,
    lastUpdated: new Date(),
    dataSource: {
      url: "https://data.insideairbnb.com/portugal/norte/porto/2025-03-15/data/listings.csv.gz",
      scrapedDate: "2025-03-15",
    },
    priceBreakdown: {
      entirePlace: 65.0,
      privateRoom: 39.6,
      sharedRoom: 28.5,
    },
  },
  {
    id: "winnipeg",
    cityName: "Winnipeg",
    country: "Canada",
    region: "Manitoba",
    averagePrice: 68.9,
    currency: "USD",
    totalListings: 890,
    lastUpdated: new Date(),
    dataSource: {
      url: "https://data.insideairbnb.com/canada/mb/winnipeg/2025-03-07/data/listings.csv.gz",
      scrapedDate: "2025-03-07",
    },
    priceBreakdown: {
      entirePlace: 85.4,
      privateRoom: 52.4,
      sharedRoom: 35.0,
    },
  },
  {
    id: "antwerp",
    cityName: "Antwerp",
    country: "Belgium",
    region: "Flemish Region",
    averagePrice: 78.2,
    currency: "USD",
    totalListings: 1560,
    lastUpdated: new Date(),
    dataSource: {
      url: "https://data.insideairbnb.com/belgium/vlg/antwerp/2025-03-21/data/listings.csv.gz",
      scrapedDate: "2025-03-21",
    },
    priceBreakdown: {
      entirePlace: 95.6,
      privateRoom: 60.8,
      sharedRoom: 42.0,
    },
  },
  {
    id: "asheville",
    cityName: "Asheville",
    country: "United States",
    region: "North Carolina",
    averagePrice: 112.5,
    currency: "USD",
    totalListings: 2340,
    lastUpdated: new Date(),
    dataSource: {
      url: "https://data.insideairbnb.com/united-states/nc/asheville/2025-03-13/data/listings.csv.gz",
      scrapedDate: "2025-03-13",
    },
    priceBreakdown: {
      entirePlace: 145.2,
      privateRoom: 79.8,
      sharedRoom: 55.0,
    },
  },
  {
    id: "albany",
    cityName: "Albany",
    country: "United States",
    region: "New York",
    averagePrice: 114.14,
    currency: "USD",
    totalListings: 413,
    lastUpdated: new Date(),
    dataSource: {
      url: "https://data.insideairbnb.com/united-states/ny/albany/2025-05-02/data/listings.csv.gz",
      scrapedDate: "2025-05-02",
    },
    priceBreakdown: {
      entirePlace: 133.17,
      privateRoom: 63.6,
      sharedRoom: 0,
    },
  },
  {
    id: "amsterdam",
    cityName: "Amsterdam",
    country: "Netherlands",
    region: "North Holland",
    averagePrice: 145.8,
    currency: "USD",
    totalListings: 15600,
    lastUpdated: new Date(),
    dataSource: {
      url: "https://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2025-03-02/data/listings.csv.gz",
      scrapedDate: "2025-03-02",
    },
    priceBreakdown: {
      entirePlace: 175.9,
      privateRoom: 115.7,
      sharedRoom: 65.0,
    },
  },
  {
    id: "zurich",
    cityName: "Zurich",
    country: "Switzerland",
    region: "Zürich",
    averagePrice: 195.4,
    currency: "USD",
    totalListings: 4200,
    lastUpdated: new Date(),
    dataSource: {
      url: "https://data.insideairbnb.com/switzerland/zürich/zurich/2025-03-23/data/listings.csv.gz",
      scrapedDate: "2025-03-23",
    },
    priceBreakdown: {
      entirePlace: 240.8,
      privateRoom: 150.0,
      sharedRoom: 85.6,
    },
  },
];
